name: Convert Markdown with Mermaid to PDF

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install markdown-it and markdown-it-mermaid
      run: npm install markdown-it markdown-it-mermaid 

    - name: Convert Markdown to HTML
      run: node convert-md-to-html.js

    - name: Upload HTML file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-file
        path: cool-root-doc.html