name: Convert Markdown with Mermaid to PDF

on:
  push:
    paths:
      - '**/*.md'
  workflow_dispatch:

jobs:
  convert_md_to_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pandoc
      run: |
        sudo apt-get install -y pandoc texlive-xetex
        npm install -g @mermaid-js/mermaid-cli

    - name: install mermaid-filter and Convert Markdown to PDF
      run: |
        pip install pandoc-mermaid-filter
        for file in $(find . -name '*.md'); do
          pdf_file="${file%.md}.pdf"
          pandoc --filter=pandoc-mermaid-filter "$file" -o "$pdf_file" --pdf-engine=xelatex
        done

    - name: Upload PDFs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: converted-pdfs
        path: '**/*.pdf'
